"""initialize

Revision ID: 1af46aba0207
Revises: 
Create Date: 2025-04-15 18:12:06.625326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1af46aba0207'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NETWORK_INFRASTRUCTURE',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_access_point_id', sa.String(), nullable=True),
    sa.Column('device_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_access_point_id'], ['NETWORK_INFRASTRUCTURE.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('USERS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(), nullable=False),
    sa.Column('role', sa.Enum('CONSULTANT', 'SERVICEMAN', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('current_session_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CUSTOMER',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('access_point', sa.String(), nullable=False),
    sa.Column('monthly_amount_due', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['access_point'], ['NETWORK_INFRASTRUCTURE.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TELEMETRY_DOWNTIME_LOG',
    sa.Column('downtime_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('access_point_id', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['access_point_id'], ['NETWORK_INFRASTRUCTURE.id'], ),
    sa.PrimaryKeyConstraint('downtime_id')
    )
    op.create_table('INVOICES',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('month', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['CUSTOMER.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('INVOICE_LINES',
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Enum('SUBSCRIPTION', 'REBATE', name='invoicelinetitle'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['INVOICES.id'], ),
    sa.PrimaryKeyConstraint('invoice_id', 'line_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('INVOICE_LINES')
    op.drop_table('INVOICES')
    op.drop_table('TELEMETRY_DOWNTIME_LOG')
    op.drop_table('CUSTOMER')
    op.drop_table('USERS')
    op.drop_table('NETWORK_INFRASTRUCTURE')
    # ### end Alembic commands ###
